# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://corpusmusic.shaffermusic.com
title: Computational Music Analysis
subtitle: "CUâ€“Boulder, May 2016"
author: Kris Shaffer
simple_search: http://google.com/search
description:
email: kris.shaffer@colorado.edu

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
markdown: kramdown
permalink: pretty

social:
  - title: twitter
    url: https://twitter.com/krisshaffer
  - title: github
    url: https://github.com/corpusmusic
